import React, { ReactNode } from 'react'
import Navbar from '@/components/ui/navbar'
import Sidebar from '@/components/ui/sidebar'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Video Conference App",
  icons:"/icons/Logo.png",
  description: "Generated by create next app",
};

const HomeLayout = ({children} : {children : ReactNode}) => {
  return (
    <main className='relative'>
        <Navbar />
        <div className='flex'>
            <Sidebar/>
            <section className='flex min-h-screen flex-1 flex-col px-6 pb-6 pt-28 max-md:pb-14 sm:px-14'>
                <div className='w-full'>
                    {children}
                </div>
            </section>
        </div> 
    </main>
  )
}

export default HomeLayout