import React, { ReactNode } from 'react'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs';
import { Toaster } from "@/components/ui/toaster";
import '@stream-io/video-react-sdk/dist/css/styles.css';
import "react-datepicker/dist/react-datepicker.css";                         
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Video Conference App",
  icons:"/icons/Logo.png",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider 
     appearance={{
      layout:{
          logoImageUrl:'/icons/Logo.png',
      },
      variables:{
        colorText:'#fff',
        colorPrimary:'#0E7859',
        colorBackground:'#1c1f2e',
        colorInputBackground:'#242a41',
        colorInputText:'#fff',
      }
     }}
    >
    <html lang="en">
      <body className={`${inter.className} bg-dark-1`}>
        {children}
        <Toaster/>
        </body>
    </html>
    </ClerkProvider>
  );
}



// const RootLayout = ({children} : {children : ReactNode}) => {
//   return (
//     <main>
//         {children}  
//     </main>
//   )
// }

// export default RootLayout

// import React from 'react'

// const Meetings =({ params }: { params: {slug: string } }) => {
//   return (
//     <div> Meetings Room : {params.slug}</div>
//   )
// }

// export default Meetings path:meeting/slug/
